name: Check code quality
on: push

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:11
        ports: ["5432:5432"]
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    name: run tests and format checks
    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1.17.3
        with:
          otp-version: "25.2"
          elixir-version: "1.16.1"
      - run: mix format --check-formatted
      - run: mix deps.get
      - run: mix compile --warnings-as-errors
      - run: mix credo
      - run: mix dialyzer
      - run: mix test
      
